# NOTE: This will not work to start the prod container, as it is missing
#       all the secrets and environment variables. Will do this later,
#       once everyything is working in staging.

services:
  # Main Next.js application service, for production only
  volunteer-next:
    networks:
      - volunteer-next
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    image: volunteer-next:latest
    container_name: volunteer-next
    environment:
      NODE_ENV: production
      PORT: "3000"
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - uploads:/app/uploads

volumes:
  uploads:

networks:
  volunteer-next:
