services:
  # Postgres service with pg_cron extension
  db:
    networks:
      - volunteer-next
    build:
      context: ./db/docker
      dockerfile: Dockerfile
    restart: always
    command: postgres -c shared_preload_libraries=pg_cron -c cron.database_name=${POSTGRES_DB}
    env_file:
      - .env.local
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql

  # Liquibase service to run database migrations
  liquibase:
    networks:
      - volunteer-next
    image: liquibase/liquibase
    volumes:
      - ./db/changelog.xml:/liquibase/changelog.xml
      - ./db/scripts:/liquibase/scripts
      - ./db/drivers:/liquibase/lib
    command: >
      --classpath=/liquibase/lib/postgresql.jar
      --url=jdbc:postgresql://db:${POSTGRES_PORT}/${POSTGRES_DB}
      --changeLogFile=changelog.xml
      --username=postgres
      --password=${POSTGRES_PASSWORD}
      update
    depends_on:
      - db

  # Mailer service, responsible for sending emails
  mailer:
    networks:
      - volunteer-next
    build:
      context: ./mailer
      dockerfile: docker/Dockerfile
    image: volunteer-next-mailer:latest
    container_name: volunteer-next-mailer
    environment:
      CRON_SCHEDULE: "*/10 * * * * *"
      RATE_LIMIT: 100
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_FROM: ${SMTP_FROM}
      FAKE_SEND: true
    restart: unless-stopped
    depends_on:
      - db

  # Upload Cleaner service, responsible for cleaning up unreferenced uploaded files
  upload-cleaner:
    networks:
      - volunteer-next
    build:
      context: ./upload-cleaner
      dockerfile: docker/Dockerfile
    image: volunteer-next-upload-cleaner:latest
    container_name: volunteer-next-upload-cleaner
    environment:
      CRON_SCHEDULE: "0 * * * *"
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      UPLOADS_DIR: /uploads
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./uploads:/uploads

volumes:
  pgdata:

networks:
  volunteer-next:
